### PR TITLE
Disable server version checking for before 5.5.0

### PR DESCRIPTION
**Pull request by emreyigit**
Removed the version verification over maven repo on the script since the tests are based on locally build Hazelcast.

### CODE REVIEW

**Comment by JackPGreen** [comment]
Could explain this change, please?

**Comment by emreyigit** [comment]
Updated the description @JackPGreen fyi.

**Comment by JackPGreen** [comment]
I think this tries to address the same issue as https://github.com/hazelcast/client-compatibility-suites/pull/112, but with a smaller scope.

I think the latter solution is more maintainable (in my biased opinion), though so I'd prefer that instead.

**Comment by emreyigit** [comment]
Sure, I've reviewed the #112 and shared my concerns there. If that is ok for you, fine by me.

**Pull request closed without merging**
